#ifndef ZSWITCH_EVENTS_H
#define ZSWITCH_EVENTS_H

enum EVENTS {
    ON_CONFIGURATION_CHANGED,
    ON_LOOP,
    ON_SETUP,
    ON_INIT,
    ON_WIFI_CONNECTED,
    ON_WIFI_DISCONNECTED,
};

#endif  //ZSWITCH_EVENTS_H