#ifndef ZSWITCH_EVENTS_H
#define ZSWITCH_EVENTS_H

#include "Gang.h"

enum EVENTS {
    ON_CONFIGURATION_CHANGED,
    ON_LOOP,
    ON_SETUP,
    ON_INIT,
    ON_WIFI_CONNECTED,
    ON_WIFI_DISCONNECTED,
    ON_KEY_TOGGLE,
    ON_SWITCH_CMD,
    ON_SWITCH_STATE
};

#endif  //ZSWITCH_EVENTS_H